### ISSUE TITLE
Update babel-core dependency to avoid warning on npm install

### ISSUE THREAD

**Issue by martinmine** [appium/appium-fake-driver#10]
appium-fake-driver has a dependency `"babel-core": "5.8.24"` which has an outdated dependency minimatch. When running `npm install`, I get the following warning in the console:
`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

Would be great if this dependency could be updated to avoid this issue.

**Comment by imurchie** [comment]
There is no real issue. The package is only used internally. Updating Babel will take a lot of work that, frankly, we don't have the resources for, unfortunately.

**Comment by rkavalap** [comment]
Closing this issue. This will be covered in the timeframe from appium 2.0 
https://github.com/appium/appium/issues/7175
